lannguage: node_js
node_js:
  - stable
  - node
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true
script:
  - yarn
  - yarn test
  - yarn run build
